using JobMarket.Data.Entity;
using System;
using System.Collections.Generic;
using System.Text;

namespace JobMarket.Ef.Util
{
    public class CurrencyLister
    {
        public ICollection<Currency> GetCurrencies()
        {
            return new Currency[]
            {
                new Currency { Id = 1, Code = "USD", Name = "United States Dollar" },
                new Currency { Id = 2, Code = "AFN", Name = "Afghan Afghani" },
                new Currency { Id = 3, Code = "ALL", Name = "Albanian Lek" },
                new Currency { Id = 4, Code = "AMD", Name = "Armenian Dram" },
                new Currency { Id = 5, Code = "ANG", Name = "Netherlands Antillean Guilder" },
                new Currency { Id = 6, Code = "AOA", Name = "Angolan Kwanza" },
                new Currency { Id = 7, Code = "ARS", Name = "Argentine Peso" },
                new Currency { Id = 8, Code = "AUD", Name = "Australian Dollar" },
                new Currency { Id = 9, Code = "AWG", Name = "Aruban Florin" },
                new Currency { Id = 10, Code = "AZN", Name = "Azerbaijani Manat" },
                new Currency { Id = 11, Code = "BAM", Name = "Bosnia-Herzegovina Convertible Mark" },
                new Currency { Id = 12, Code = "BBD", Name = "Barbadian Dollar" },
                new Currency { Id = 13, Code = "BDT", Name = "Bangladeshi Taka" },
                new Currency { Id = 14, Code = "BGN", Name = "Bulgarian Lev" },
                new Currency { Id = 15, Code = "BHD", Name = "Bahraini Dinar" },
                new Currency { Id = 16, Code = "BIF", Name = "Burundian Franc" },
                new Currency { Id = 17, Code = "BMD", Name = "Bermudian Dollar" },
                new Currency { Id = 18, Code = "BND", Name = "Brunei Dollar" },
                new Currency { Id = 19, Code = "BOB", Name = "Bolivian Boliviano" },
                new Currency { Id = 20, Code = "BRL", Name = "Brazilian Real" },
                new Currency { Id = 21, Code = "BSD", Name = "Bahamian Dollar" },
                new Currency { Id = 22, Code = "BTN", Name = "Bhutanese Ngultrum" },
                new Currency { Id = 23, Code = "BWP", Name = "Botswana Pula" },
                new Currency { Id = 24, Code = "BYN", Name = "Belarusian Ruble" },
                new Currency { Id = 25, Code = "BZD", Name = "Belize Dollar" },
                new Currency { Id = 26, Code = "CAD", Name = "Canadian Dollar" },
                new Currency { Id = 27, Code = "CDF", Name = "Congolese Franc" },
                new Currency { Id = 28, Code = "CHF", Name = "Swiss Franc" },
                new Currency { Id = 29, Code = "CLP", Name = "Chilean Peso" },
                new Currency { Id = 30, Code = "CNY", Name = "Chinese Yuan" },
                new Currency { Id = 31, Code = "COP", Name = "Colombian Peso" },
                new Currency { Id = 32, Code = "CRC", Name = "Costa Rican Colon" },
                new Currency { Id = 33, Code = "CUP", Name = "Cuban Peso" },
                new Currency { Id = 34, Code = "CVE", Name = "Cape Verdean Escudo" },
                new Currency { Id = 35, Code = "CZK", Name = "Czech Koruna" },
                new Currency { Id = 36, Code = "DJF", Name = "Djiboutian Franc" },
                new Currency { Id = 37, Code = "DKK", Name = "Danish Krone" },
                new Currency { Id = 38, Code = "DOP", Name = "Dominican Peso" },
                new Currency { Id = 39, Code = "DZD", Name = "Algerian Dinar" },
                new Currency { Id = 40, Code = "EGP", Name = "Egyptian Pound" },
                new Currency { Id = 41, Code = "ERN", Name = "Eritrean Nakfa" },
                new Currency { Id = 42, Code = "ETB", Name = "Ethiopian Birr" },
                new Currency { Id = 43, Code = "EUR", Name = "Euro" },
                new Currency { Id = 44, Code = "FJD", Name = "Fijian Dollar" },
                new Currency { Id = 45, Code = "FKP", Name = "Falkland Islands Pound" },
                new Currency { Id = 46, Code = "GBP", Name = "British Pound Sterling" },
                new Currency { Id = 47, Code = "GEL", Name = "Georgian Lari" },
                new Currency { Id = 48, Code = "GHS", Name = "Ghanaian Cedi" },
                new Currency { Id = 49, Code = "GIP", Name = "Gibraltar Pound" },
                new Currency { Id = 50, Code = "GMD", Name = "Gambian Dalasi" },
                new Currency { Id = 51, Code = "GNF", Name = "Guinean Franc" },
                new Currency { Id = 52, Code = "GTQ", Name = "Guatemalan Quetzal" },
                new Currency { Id = 53, Code = "GYD", Name = "Guyanese Dollar" },
                new Currency { Id = 54, Code = "HKD", Name = "Hong Kong Dollar" },
                new Currency { Id = 55, Code = "HNL", Name = "Honduran Lempira" },
                new Currency { Id = 56, Code = "HRK", Name = "Croatian Kuna" },
                new Currency { Id = 57, Code = "HTG", Name = "Haitian Gourde" },
                new Currency { Id = 58, Code = "HUF", Name = "Hungarian Forint" },
                new Currency { Id = 59, Code = "IdR", Name = "Indonesian Rupiah" },
                new Currency { Id = 60, Code = "ILS", Name = "Israeli New Shekel" },
                new Currency { Id = 61, Code = "INR", Name = "Indian Rupee" },
                new Currency { Id = 62, Code = "IQD", Name = "Iraqi Dinar" },
                new Currency { Id = 63, Code = "IRR", Name = "Iranian Rial" },
                new Currency { Id = 64, Code = "ISK", Name = "Icelandic Krona" },
                new Currency { Id = 65, Code = "JMD", Name = "Jamaican Dollar" },
                new Currency { Id = 66, Code = "JOD", Name = "Jordanian Dinar" },
                new Currency { Id = 67, Code = "JPY", Name = "Japanese Yen" },
                new Currency { Id = 68, Code = "KES", Name = "Kenyan Shilling" },
                new Currency { Id = 69, Code = "KGS", Name = "Kyrgyzstani Som" },
                new Currency { Id = 70, Code = "KHR", Name = "Cambodian Riel" },
                new Currency { Id = 71, Code = "KMF", Name = "Comorian Franc" },
                new Currency { Id = 72, Code = "KPW", Name = "North Korean Won" },
                new Currency { Id = 73, Code = "KRW", Name = "South Korean Won" },
                new Currency { Id = 74, Code = "KWD", Name = "Kuwaiti Dinar" },
                new Currency { Id = 75, Code = "KYD", Name = "Cayman Islands Dollar" },
                new Currency { Id = 76, Code = "KZT", Name = "Kazakhstani Tenge" },
                new Currency { Id = 77, Code = "LAK", Name = "Lao Kip" },
                new Currency { Id = 78, Code = "LBP", Name = "Lebanese Pound" },
                new Currency { Id = 79, Code = "LKR", Name = "Sri Lankan Rupee" },
                new Currency { Id = 80, Code = "LRD", Name = "Liberian Dollar" },
                new Currency { Id = 81, Code = "LSL", Name = "Lesotho Loti" },
                new Currency { Id = 82, Code = "LYD", Name = "Libyan Dinar" },
                new Currency { Id = 83, Code = "MAD", Name = "Moroccan Dirham" },
                new Currency { Id = 84, Code = "MDL", Name = "Moldovan Leu" },
                new Currency { Id = 85, Code = "MGA", Name = "Malagasy Ariary" },
                new Currency { Id = 86, Code = "MKD", Name = "Macedonian Denar" },
                new Currency { Id = 87, Code = "MMK", Name = "Myanmar Kyat" },
                new Currency { Id = 88, Code = "MNT", Name = "Mongolian Tugrik" },
                new Currency { Id = 89, Code = "MOP", Name = "Macanese Pataca" },
                new Currency { Id = 90, Code = "MRU", Name = "Mauritanian Ouguiya" },
                new Currency { Id = 91, Code = "MUR", Name = "Mauritian Rupee" },
                new Currency { Id = 92, Code = "MVR", Name = "Maldivian Rufiyaa" },
                new Currency { Id = 93, Code = "MWK", Name = "Malawian Kwacha" },
                new Currency { Id = 94, Code = "MXN", Name = "Mexican Peso" },
                new Currency { Id = 95, Code = "MYR", Name = "Malaysian Ringgit" },
                new Currency { Id = 96, Code = "MZN", Name = "Mozambican Metical" },
                new Currency { Id = 97, Code = "NAD", Name = "Namibian Dollar" },
                new Currency { Id = 98, Code = "NGN", Name = "Nigerian Naira" },
                new Currency { Id = 99, Code = "NIO", Name = "Nicaraguan Córdoba" },
                new Currency { Id = 100, Code = "NOK", Name = "Norwegian Krone" },
                new Currency { Id = 101, Code = "NPR", Name = "Nepalese Rupee" },
                new Currency { Id = 102, Code = "NZD", Name = "New Zealand Dollar" },
                new Currency { Id = 103, Code = "OMR", Name = "Omani Rial" },
                new Currency { Id = 104, Code = "PAB", Name = "Panamanian Balboa" },
                new Currency { Id = 105, Code = "PEN", Name = "Peruvian Sol" },
                new Currency { Id = 106, Code = "PGK", Name = "Papua New Guinean Kina" },
                new Currency { Id = 107, Code = "PHP", Name = "Philippine Peso" },
                new Currency { Id = 108, Code = "PKR", Name = "Pakistani Rupee" },
                new Currency { Id = 109, Code = "PLN", Name = "Polish Zloty" },
                new Currency { Id = 110, Code = "PYG", Name = "Paraguayan Guarani" },
                new Currency { Id = 111, Code = "QAR", Name = "Qatari Riyal" },
                new Currency { Id = 112, Code = "RON", Name = "Romanian Leu" },
                new Currency { Id = 113, Code = "RSD", Name = "Serbian Dinar" },
                new Currency { Id = 114, Code = "RUB", Name = "Russian Ruble" },
                new Currency { Id = 115, Code = "RWF", Name = "Rwandan Franc" },
                new Currency { Id = 116, Code = "SAR", Name = "Saudi Riyal" },
                new Currency { Id = 117, Code = "SBD", Name = "Solomon Islands Dollar" },
                new Currency { Id = 118, Code = "SCR", Name = "Seychellois Rupee" },
                new Currency { Id = 119, Code = "SDG", Name = "Sudanese Pound" },
                new Currency { Id = 120, Code = "SEK", Name = "Swedish Krona" },
                new Currency { Id = 121, Code = "SGD", Name = "Singapore Dollar" },
                new Currency { Id = 122, Code = "SHP", Name = "Saint Helena Pound" },
                new Currency { Id = 123, Code = "SLL", Name = "Sierra Leonean Leone" },
                new Currency { Id = 124, Code = "SOS", Name = "Somali Shilling" },
                new Currency { Id = 125, Code = "SRD", Name = "Surinamese Dollar" },
                new Currency { Id = 126, Code = "SSP", Name = "South Sudanese Pound" },
                new Currency { Id = 127, Code = "STN", Name = "São Tomé and Príncipe Dobra" },
                new Currency { Id = 128, Code = "SVC", Name = "Salvadoran Colón" },
                new Currency { Id = 129, Code = "SYP", Name = "Syrian Pound" },
                new Currency { Id = 130, Code = "SZL", Name = "Swazi Lilangeni" },
                new Currency { Id = 131, Code = "THB", Name = "Thai Baht" },
                new Currency { Id = 132, Code = "TJS", Name = "Tajikistani Somoni" },
                new Currency { Id = 133, Code = "TMT", Name = "Turkmenistani Manat" },
                new Currency { Id = 134, Code = "TND", Name = "Tunisian Dinar" },
                new Currency { Id = 135, Code = "TOP", Name = "Tongan Paʻanga" },
                new Currency { Id = 136, Code = "TRY", Name = "Turkish Lira" },
                new Currency { Id = 137, Code = "TTD", Name = "TrinIdad and Tobago Dollar" },
                new Currency { Id = 138, Code = "TWD", Name = "New Taiwan Dollar" },
                new Currency { Id = 139, Code = "TZS", Name = "Tanzanian Shilling" },
                new Currency { Id = 140, Code = "UAH", Name = "Ukrainian Hryvnia" },
                new Currency { Id = 141, Code = "UGX", Name = "Ugandan Shilling" },
                new Currency { Id = 142, Code = "AED", Name = "United Arab Emirates Dirham" },
                new Currency { Id = 143, Code = "UYU", Name = "Uruguayan Peso" },
                new Currency { Id = 144, Code = "UZS", Name = "Uzbekistani Som" },
                new Currency { Id = 145, Code = "VES", Name = "Venezuelan Bolívar" },
                new Currency { Id = 146, Code = "VND", Name = "Vietnamese Dong" },
                new Currency { Id = 147, Code = "VUV", Name = "Vanuatu Vatu" },
                new Currency { Id = 148, Code = "WST", Name = "Samoan Tala" },
                new Currency { Id = 149, Code = "XAF", Name = "Central African CFA Franc" },
                new Currency { Id = 150, Code = "XCD", Name = "East Caribbean Dollar" },
                new Currency { Id = 151, Code = "XOF", Name = "West African CFA Franc" },
                new Currency { Id = 152, Code = "XPF", Name = "CFP Franc" },
                new Currency { Id = 153, Code = "YER", Name = "Yemeni Rial" },
                new Currency { Id = 154, Code = "ZAR", Name = "South African Rand" },
                new Currency { Id = 155, Code = "ZMW", Name = "Zambian Kwacha" },
                new Currency { Id = 156, Code = "ZWL", Name = "Zimbabwean Dollar" }
            };
        }
    }
}
