// <auto-generated />
using System;
using JobMarket.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsOnMarket.Migrations
{
    [DbContext(typeof(JobMarketContext))]
    [Migration("20260220163717_currencies")]
    partial class currencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobMarket.Data.Entity.Contractor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contractor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Acme co",
                            Rating = 3
                        },
                        new
                        {
                            ID = 2,
                            Name = "Generic Co",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.ContractorUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorUser");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ContractorId = 1,
                            UserId = "8e445800-1111-4543-1111-9443d048cdb9"
                        },
                        new
                        {
                            ID = 2,
                            ContractorId = 2,
                            UserId = "8e445801-1111-4543-1111-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Name = "United States Dollar"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AFN",
                            Name = "Afghan Afghani"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ALL",
                            Name = "Albanian Lek"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AMD",
                            Name = "Armenian Dram"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ANG",
                            Name = "Netherlands Antillean Guilder"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AOA",
                            Name = "Angolan Kwanza"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ARS",
                            Name = "Argentine Peso"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AUD",
                            Name = "Australian Dollar"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AWG",
                            Name = "Aruban Florin"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AZN",
                            Name = "Azerbaijani Manat"
                        },
                        new
                        {
                            Id = 11,
                            Code = "BAM",
                            Name = "Bosnia-Herzegovina Convertible Mark"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BBD",
                            Name = "Barbadian Dollar"
                        },
                        new
                        {
                            Id = 13,
                            Code = "BDT",
                            Name = "Bangladeshi Taka"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BGN",
                            Name = "Bulgarian Lev"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BHD",
                            Name = "Bahraini Dinar"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BIF",
                            Name = "Burundian Franc"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BMD",
                            Name = "Bermudian Dollar"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BND",
                            Name = "Brunei Dollar"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BOB",
                            Name = "Bolivian Boliviano"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BRL",
                            Name = "Brazilian Real"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BSD",
                            Name = "Bahamian Dollar"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BTN",
                            Name = "Bhutanese Ngultrum"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BWP",
                            Name = "Botswana Pula"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BYN",
                            Name = "Belarusian Ruble"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BZD",
                            Name = "Belize Dollar"
                        },
                        new
                        {
                            Id = 26,
                            Code = "CAD",
                            Name = "Canadian Dollar"
                        },
                        new
                        {
                            Id = 27,
                            Code = "CDF",
                            Name = "Congolese Franc"
                        },
                        new
                        {
                            Id = 28,
                            Code = "CHF",
                            Name = "Swiss Franc"
                        },
                        new
                        {
                            Id = 29,
                            Code = "CLP",
                            Name = "Chilean Peso"
                        },
                        new
                        {
                            Id = 30,
                            Code = "CNY",
                            Name = "Chinese Yuan"
                        },
                        new
                        {
                            Id = 31,
                            Code = "COP",
                            Name = "Colombian Peso"
                        },
                        new
                        {
                            Id = 32,
                            Code = "CRC",
                            Name = "Costa Rican Colon"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CUP",
                            Name = "Cuban Peso"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CVE",
                            Name = "Cape Verdean Escudo"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CZK",
                            Name = "Czech Koruna"
                        },
                        new
                        {
                            Id = 36,
                            Code = "DJF",
                            Name = "Djiboutian Franc"
                        },
                        new
                        {
                            Id = 37,
                            Code = "DKK",
                            Name = "Danish Krone"
                        },
                        new
                        {
                            Id = 38,
                            Code = "DOP",
                            Name = "Dominican Peso"
                        },
                        new
                        {
                            Id = 39,
                            Code = "DZD",
                            Name = "Algerian Dinar"
                        },
                        new
                        {
                            Id = 40,
                            Code = "EGP",
                            Name = "Egyptian Pound"
                        },
                        new
                        {
                            Id = 41,
                            Code = "ERN",
                            Name = "Eritrean Nakfa"
                        },
                        new
                        {
                            Id = 42,
                            Code = "ETB",
                            Name = "Ethiopian Birr"
                        },
                        new
                        {
                            Id = 43,
                            Code = "EUR",
                            Name = "Euro"
                        },
                        new
                        {
                            Id = 44,
                            Code = "FJD",
                            Name = "Fijian Dollar"
                        },
                        new
                        {
                            Id = 45,
                            Code = "FKP",
                            Name = "Falkland Islands Pound"
                        },
                        new
                        {
                            Id = 46,
                            Code = "GBP",
                            Name = "British Pound Sterling"
                        },
                        new
                        {
                            Id = 47,
                            Code = "GEL",
                            Name = "Georgian Lari"
                        },
                        new
                        {
                            Id = 48,
                            Code = "GHS",
                            Name = "Ghanaian Cedi"
                        },
                        new
                        {
                            Id = 49,
                            Code = "GIP",
                            Name = "Gibraltar Pound"
                        },
                        new
                        {
                            Id = 50,
                            Code = "GMD",
                            Name = "Gambian Dalasi"
                        },
                        new
                        {
                            Id = 51,
                            Code = "GNF",
                            Name = "Guinean Franc"
                        },
                        new
                        {
                            Id = 52,
                            Code = "GTQ",
                            Name = "Guatemalan Quetzal"
                        },
                        new
                        {
                            Id = 53,
                            Code = "GYD",
                            Name = "Guyanese Dollar"
                        },
                        new
                        {
                            Id = 54,
                            Code = "HKD",
                            Name = "Hong Kong Dollar"
                        },
                        new
                        {
                            Id = 55,
                            Code = "HNL",
                            Name = "Honduran Lempira"
                        },
                        new
                        {
                            Id = 56,
                            Code = "HRK",
                            Name = "Croatian Kuna"
                        },
                        new
                        {
                            Id = 57,
                            Code = "HTG",
                            Name = "Haitian Gourde"
                        },
                        new
                        {
                            Id = 58,
                            Code = "HUF",
                            Name = "Hungarian Forint"
                        },
                        new
                        {
                            Id = 59,
                            Code = "IdR",
                            Name = "Indonesian Rupiah"
                        },
                        new
                        {
                            Id = 60,
                            Code = "ILS",
                            Name = "Israeli New Shekel"
                        },
                        new
                        {
                            Id = 61,
                            Code = "INR",
                            Name = "Indian Rupee"
                        },
                        new
                        {
                            Id = 62,
                            Code = "IQD",
                            Name = "Iraqi Dinar"
                        },
                        new
                        {
                            Id = 63,
                            Code = "IRR",
                            Name = "Iranian Rial"
                        },
                        new
                        {
                            Id = 64,
                            Code = "ISK",
                            Name = "Icelandic Krona"
                        },
                        new
                        {
                            Id = 65,
                            Code = "JMD",
                            Name = "Jamaican Dollar"
                        },
                        new
                        {
                            Id = 66,
                            Code = "JOD",
                            Name = "Jordanian Dinar"
                        },
                        new
                        {
                            Id = 67,
                            Code = "JPY",
                            Name = "Japanese Yen"
                        },
                        new
                        {
                            Id = 68,
                            Code = "KES",
                            Name = "Kenyan Shilling"
                        },
                        new
                        {
                            Id = 69,
                            Code = "KGS",
                            Name = "Kyrgyzstani Som"
                        },
                        new
                        {
                            Id = 70,
                            Code = "KHR",
                            Name = "Cambodian Riel"
                        },
                        new
                        {
                            Id = 71,
                            Code = "KMF",
                            Name = "Comorian Franc"
                        },
                        new
                        {
                            Id = 72,
                            Code = "KPW",
                            Name = "North Korean Won"
                        },
                        new
                        {
                            Id = 73,
                            Code = "KRW",
                            Name = "South Korean Won"
                        },
                        new
                        {
                            Id = 74,
                            Code = "KWD",
                            Name = "Kuwaiti Dinar"
                        },
                        new
                        {
                            Id = 75,
                            Code = "KYD",
                            Name = "Cayman Islands Dollar"
                        },
                        new
                        {
                            Id = 76,
                            Code = "KZT",
                            Name = "Kazakhstani Tenge"
                        },
                        new
                        {
                            Id = 77,
                            Code = "LAK",
                            Name = "Lao Kip"
                        },
                        new
                        {
                            Id = 78,
                            Code = "LBP",
                            Name = "Lebanese Pound"
                        },
                        new
                        {
                            Id = 79,
                            Code = "LKR",
                            Name = "Sri Lankan Rupee"
                        },
                        new
                        {
                            Id = 80,
                            Code = "LRD",
                            Name = "Liberian Dollar"
                        },
                        new
                        {
                            Id = 81,
                            Code = "LSL",
                            Name = "Lesotho Loti"
                        },
                        new
                        {
                            Id = 82,
                            Code = "LYD",
                            Name = "Libyan Dinar"
                        },
                        new
                        {
                            Id = 83,
                            Code = "MAD",
                            Name = "Moroccan Dirham"
                        },
                        new
                        {
                            Id = 84,
                            Code = "MDL",
                            Name = "Moldovan Leu"
                        },
                        new
                        {
                            Id = 85,
                            Code = "MGA",
                            Name = "Malagasy Ariary"
                        },
                        new
                        {
                            Id = 86,
                            Code = "MKD",
                            Name = "Macedonian Denar"
                        },
                        new
                        {
                            Id = 87,
                            Code = "MMK",
                            Name = "Myanmar Kyat"
                        },
                        new
                        {
                            Id = 88,
                            Code = "MNT",
                            Name = "Mongolian Tugrik"
                        },
                        new
                        {
                            Id = 89,
                            Code = "MOP",
                            Name = "Macanese Pataca"
                        },
                        new
                        {
                            Id = 90,
                            Code = "MRU",
                            Name = "Mauritanian Ouguiya"
                        },
                        new
                        {
                            Id = 91,
                            Code = "MUR",
                            Name = "Mauritian Rupee"
                        },
                        new
                        {
                            Id = 92,
                            Code = "MVR",
                            Name = "Maldivian Rufiyaa"
                        },
                        new
                        {
                            Id = 93,
                            Code = "MWK",
                            Name = "Malawian Kwacha"
                        },
                        new
                        {
                            Id = 94,
                            Code = "MXN",
                            Name = "Mexican Peso"
                        },
                        new
                        {
                            Id = 95,
                            Code = "MYR",
                            Name = "Malaysian Ringgit"
                        },
                        new
                        {
                            Id = 96,
                            Code = "MZN",
                            Name = "Mozambican Metical"
                        },
                        new
                        {
                            Id = 97,
                            Code = "NAD",
                            Name = "Namibian Dollar"
                        },
                        new
                        {
                            Id = 98,
                            Code = "NGN",
                            Name = "Nigerian Naira"
                        },
                        new
                        {
                            Id = 99,
                            Code = "NIO",
                            Name = "Nicaraguan Córdoba"
                        },
                        new
                        {
                            Id = 100,
                            Code = "NOK",
                            Name = "Norwegian Krone"
                        },
                        new
                        {
                            Id = 101,
                            Code = "NPR",
                            Name = "Nepalese Rupee"
                        },
                        new
                        {
                            Id = 102,
                            Code = "NZD",
                            Name = "New Zealand Dollar"
                        },
                        new
                        {
                            Id = 103,
                            Code = "OMR",
                            Name = "Omani Rial"
                        },
                        new
                        {
                            Id = 104,
                            Code = "PAB",
                            Name = "Panamanian Balboa"
                        },
                        new
                        {
                            Id = 105,
                            Code = "PEN",
                            Name = "Peruvian Sol"
                        },
                        new
                        {
                            Id = 106,
                            Code = "PGK",
                            Name = "Papua New Guinean Kina"
                        },
                        new
                        {
                            Id = 107,
                            Code = "PHP",
                            Name = "Philippine Peso"
                        },
                        new
                        {
                            Id = 108,
                            Code = "PKR",
                            Name = "Pakistani Rupee"
                        },
                        new
                        {
                            Id = 109,
                            Code = "PLN",
                            Name = "Polish Zloty"
                        },
                        new
                        {
                            Id = 110,
                            Code = "PYG",
                            Name = "Paraguayan Guarani"
                        },
                        new
                        {
                            Id = 111,
                            Code = "QAR",
                            Name = "Qatari Riyal"
                        },
                        new
                        {
                            Id = 112,
                            Code = "RON",
                            Name = "Romanian Leu"
                        },
                        new
                        {
                            Id = 113,
                            Code = "RSD",
                            Name = "Serbian Dinar"
                        },
                        new
                        {
                            Id = 114,
                            Code = "RUB",
                            Name = "Russian Ruble"
                        },
                        new
                        {
                            Id = 115,
                            Code = "RWF",
                            Name = "Rwandan Franc"
                        },
                        new
                        {
                            Id = 116,
                            Code = "SAR",
                            Name = "Saudi Riyal"
                        },
                        new
                        {
                            Id = 117,
                            Code = "SBD",
                            Name = "Solomon Islands Dollar"
                        },
                        new
                        {
                            Id = 118,
                            Code = "SCR",
                            Name = "Seychellois Rupee"
                        },
                        new
                        {
                            Id = 119,
                            Code = "SDG",
                            Name = "Sudanese Pound"
                        },
                        new
                        {
                            Id = 120,
                            Code = "SEK",
                            Name = "Swedish Krona"
                        },
                        new
                        {
                            Id = 121,
                            Code = "SGD",
                            Name = "Singapore Dollar"
                        },
                        new
                        {
                            Id = 122,
                            Code = "SHP",
                            Name = "Saint Helena Pound"
                        },
                        new
                        {
                            Id = 123,
                            Code = "SLL",
                            Name = "Sierra Leonean Leone"
                        },
                        new
                        {
                            Id = 124,
                            Code = "SOS",
                            Name = "Somali Shilling"
                        },
                        new
                        {
                            Id = 125,
                            Code = "SRD",
                            Name = "Surinamese Dollar"
                        },
                        new
                        {
                            Id = 126,
                            Code = "SSP",
                            Name = "South Sudanese Pound"
                        },
                        new
                        {
                            Id = 127,
                            Code = "STN",
                            Name = "São Tomé and Príncipe Dobra"
                        },
                        new
                        {
                            Id = 128,
                            Code = "SVC",
                            Name = "Salvadoran Colón"
                        },
                        new
                        {
                            Id = 129,
                            Code = "SYP",
                            Name = "Syrian Pound"
                        },
                        new
                        {
                            Id = 130,
                            Code = "SZL",
                            Name = "Swazi Lilangeni"
                        },
                        new
                        {
                            Id = 131,
                            Code = "THB",
                            Name = "Thai Baht"
                        },
                        new
                        {
                            Id = 132,
                            Code = "TJS",
                            Name = "Tajikistani Somoni"
                        },
                        new
                        {
                            Id = 133,
                            Code = "TMT",
                            Name = "Turkmenistani Manat"
                        },
                        new
                        {
                            Id = 134,
                            Code = "TND",
                            Name = "Tunisian Dinar"
                        },
                        new
                        {
                            Id = 135,
                            Code = "TOP",
                            Name = "Tongan Paʻanga"
                        },
                        new
                        {
                            Id = 136,
                            Code = "TRY",
                            Name = "Turkish Lira"
                        },
                        new
                        {
                            Id = 137,
                            Code = "TTD",
                            Name = "TrinIdad and Tobago Dollar"
                        },
                        new
                        {
                            Id = 138,
                            Code = "TWD",
                            Name = "New Taiwan Dollar"
                        },
                        new
                        {
                            Id = 139,
                            Code = "TZS",
                            Name = "Tanzanian Shilling"
                        },
                        new
                        {
                            Id = 140,
                            Code = "UAH",
                            Name = "Ukrainian Hryvnia"
                        },
                        new
                        {
                            Id = 141,
                            Code = "UGX",
                            Name = "Ugandan Shilling"
                        },
                        new
                        {
                            Id = 142,
                            Code = "AED",
                            Name = "United Arab Emirates Dirham"
                        },
                        new
                        {
                            Id = 143,
                            Code = "UYU",
                            Name = "Uruguayan Peso"
                        },
                        new
                        {
                            Id = 144,
                            Code = "UZS",
                            Name = "Uzbekistani Som"
                        },
                        new
                        {
                            Id = 145,
                            Code = "VES",
                            Name = "Venezuelan Bolívar"
                        },
                        new
                        {
                            Id = 146,
                            Code = "VND",
                            Name = "Vietnamese Dong"
                        },
                        new
                        {
                            Id = 147,
                            Code = "VUV",
                            Name = "Vanuatu Vatu"
                        },
                        new
                        {
                            Id = 148,
                            Code = "WST",
                            Name = "Samoan Tala"
                        },
                        new
                        {
                            Id = 149,
                            Code = "XAF",
                            Name = "Central African CFA Franc"
                        },
                        new
                        {
                            Id = 150,
                            Code = "XCD",
                            Name = "East Caribbean Dollar"
                        },
                        new
                        {
                            Id = 151,
                            Code = "XOF",
                            Name = "West African CFA Franc"
                        },
                        new
                        {
                            Id = 152,
                            Code = "XPF",
                            Name = "CFP Franc"
                        },
                        new
                        {
                            Id = 153,
                            Code = "YER",
                            Name = "Yemeni Rial"
                        },
                        new
                        {
                            Id = 154,
                            Code = "ZAR",
                            Name = "South African Rand"
                        },
                        new
                        {
                            Id = 155,
                            Code = "ZMW",
                            Name = "Zambian Kwacha"
                        },
                        new
                        {
                            Id = 156,
                            Code = "ZWL",
                            Name = "Zimbabwean Dollar"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Jane",
                            LastName = "Dow"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.CustomerUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerUser");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CustomerId = 1,
                            UserId = "8e445800-0000-4543-0000-9443d048cdb9"
                        },
                        new
                        {
                            ID = 2,
                            CustomerId = 2,
                            UserId = "8e445801-0000-4543-0000-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AcceptedById")
                        .HasColumnType("int");

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<int?>("BudgetCurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AcceptedById");

                    b.HasIndex("BudgetCurrencyId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.JobOffer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("OfferedByContractorId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("PriceCurrencyId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("JobId");

                    b.HasIndex("OfferedByContractorId");

                    b.HasIndex("PriceCurrencyId");

                    b.ToTable("JobOffer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00445865-0000-0000-0000-9443d048cdb9",
                            ConcurrencyStamp = "00445865-0000-0000-0000-9443d048cd00",
                            Name = "General",
                            NormalizedName = "General"
                        },
                        new
                        {
                            Id = "8e445865-0000-0000-0000-9443d048cdb9",
                            ConcurrencyStamp = "8e445865-0000-0000-0000-9443d048cdb9",
                            Name = "Customer",
                            NormalizedName = "Customer"
                        },
                        new
                        {
                            Id = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9",
                            ConcurrencyStamp = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9",
                            Name = "Contractor",
                            NormalizedName = "Contractor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445800-0000-4543-0000-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-0000-aaaa-0000-9443d048cd00",
                            Email = "customer@customer.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@CUSTOMER.COM",
                            NormalizedUserName = "CUSTOMER@CUSTOMER.COM",
                            PasswordHash = "aPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-0000-aaaa-0000-9443d048cdb9",
                            TwoFactorEnabled = false,
                            UserName = "customer@customer.com"
                        },
                        new
                        {
                            Id = "8e445800-1111-4543-1111-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-1111-aaaa-1111-9443d048cd00",
                            Email = "Contractor@contractor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRACTOR@CONTRACTOR.COM",
                            NormalizedUserName = "CONTRACTOR@CONTRACTOR.COM",
                            PasswordHash = "bPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-1111-aaaa-1111-9443d048cdb9",
                            TwoFactorEnabled = false,
                            UserName = "Contractor@contractor.com"
                        },
                        new
                        {
                            Id = "8e445801-0000-4543-0000-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-0000-aaaa-0000-9443d048cdaa",
                            Email = "acustomer@customer.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACUSTOMER@CUSTOMER.COM",
                            NormalizedUserName = "ACUSTOMER@CUSTOMER.COM",
                            PasswordHash = "aPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-0000-aaaa-0000-9443d048cdaa",
                            TwoFactorEnabled = false,
                            UserName = "acustomer@customer.com"
                        },
                        new
                        {
                            Id = "8e445801-1111-4543-1111-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-1111-aaaa-1111-9443d048cd11",
                            Email = "acontractor@contractor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACONTRACTOR@CONTRACTOR.COM",
                            NormalizedUserName = "ACONTRACTOR@CONTRACTOR.COM",
                            PasswordHash = "bPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-1111-aaaa-1111-9443d048cd11",
                            TwoFactorEnabled = false,
                            UserName = "acontractor@contractor.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445800-0000-4543-0000-9443d048cdb9",
                            RoleId = "8e445865-0000-0000-0000-9443d048cdb9"
                        },
                        new
                        {
                            UserId = "8e445800-1111-4543-1111-9443d048cdb9",
                            RoleId = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobMarket.Data.Entity.ContractorUser", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Contractor", "AssociatedContractor")
                        .WithMany()
                        .HasForeignKey("ContractorId");

                    b.Navigation("AssociatedContractor");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.CustomerUser", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Customer", "AssociatedCustomer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("AssociatedCustomer");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Job", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Customer", "AcceptedBy")
                        .WithMany()
                        .HasForeignKey("AcceptedById");

                    b.HasOne("JobMarket.Data.Entity.Currency", "BudgetCurrency")
                        .WithMany()
                        .HasForeignKey("BudgetCurrencyId");

                    b.Navigation("AcceptedBy");

                    b.Navigation("BudgetCurrency");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.JobOffer", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Job", "OfferedJob")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMarket.Data.Entity.Contractor", "OfferedByContractor")
                        .WithMany()
                        .HasForeignKey("OfferedByContractorId");

                    b.HasOne("JobMarket.Data.Entity.Currency", "PriceCurrency")
                        .WithMany()
                        .HasForeignKey("PriceCurrencyId");

                    b.Navigation("OfferedByContractor");

                    b.Navigation("OfferedJob");

                    b.Navigation("PriceCurrency");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
