// <auto-generated />
using System;
using JobMarket.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsOnMarket.Migrations
{
    [DbContext(typeof(JobMarketContext))]
    [Migration("20260218022703_seedContractor")]
    partial class seedContractor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobMarket.Data.Entity.Contractor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contractor");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Acme co",
                            Rating = 3
                        },
                        new
                        {
                            ID = 2,
                            Name = "Generic Co",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.ContractorUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorUser");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ContractorId = 1,
                            UserId = "8e445800-1111-4543-1111-9443d048cdb9"
                        },
                        new
                        {
                            ID = 2,
                            ContractorId = 2,
                            UserId = "8e445801-1111-4543-1111-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Jane",
                            LastName = "Dow"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.CustomerUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerUser");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CustomerId = 1,
                            UserId = "8e445800-0000-4543-0000-9443d048cdb9"
                        },
                        new
                        {
                            ID = 2,
                            CustomerId = 2,
                            UserId = "8e445801-0000-4543-0000-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AcceptedById")
                        .HasColumnType("int");

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AcceptedById");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.JobOffer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("OfferedByContractorId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("JobId");

                    b.HasIndex("OfferedByContractorId");

                    b.ToTable("JobOffer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00445865-0000-0000-0000-9443d048cdb9",
                            ConcurrencyStamp = "00445865-0000-0000-0000-9443d048cd00",
                            Name = "General",
                            NormalizedName = "General"
                        },
                        new
                        {
                            Id = "8e445865-0000-0000-0000-9443d048cdb9",
                            ConcurrencyStamp = "8e445865-0000-0000-0000-9443d048cdb9",
                            Name = "Customer",
                            NormalizedName = "Customer"
                        },
                        new
                        {
                            Id = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9",
                            ConcurrencyStamp = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9",
                            Name = "Contractor",
                            NormalizedName = "Contractor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445800-0000-4543-0000-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-0000-aaaa-0000-9443d048cd00",
                            Email = "customer@customer.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@CUSTOMER.COM",
                            NormalizedUserName = "CUSTOMER@CUSTOMER.COM",
                            PasswordHash = "aPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-0000-aaaa-0000-9443d048cdb9",
                            TwoFactorEnabled = false,
                            UserName = "customer@customer.com"
                        },
                        new
                        {
                            Id = "8e445800-1111-4543-1111-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-1111-aaaa-1111-9443d048cd00",
                            Email = "Contractor@contractor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRACTOR@CONTRACTOR.COM",
                            NormalizedUserName = "CONTRACTOR@CONTRACTOR.COM",
                            PasswordHash = "bPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-1111-aaaa-1111-9443d048cdb9",
                            TwoFactorEnabled = false,
                            UserName = "Contractor@contractor.com"
                        },
                        new
                        {
                            Id = "8e445801-0000-4543-0000-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-0000-aaaa-0000-9443d048cdaa",
                            Email = "acustomer@customer.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACUSTOMER@CUSTOMER.COM",
                            NormalizedUserName = "ACUSTOMER@CUSTOMER.COM",
                            PasswordHash = "aPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-0000-aaaa-0000-9443d048cdaa",
                            TwoFactorEnabled = false,
                            UserName = "acustomer@customer.com"
                        },
                        new
                        {
                            Id = "8e445801-1111-4543-1111-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e445865-1111-aaaa-1111-9443d048cd11",
                            Email = "acontractor@contractor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACONTRACTOR@CONTRACTOR.COM",
                            NormalizedUserName = "ACONTRACTOR@CONTRACTOR.COM",
                            PasswordHash = "bPassword123!",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-1111-aaaa-1111-9443d048cd11",
                            TwoFactorEnabled = false,
                            UserName = "acontractor@contractor.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445800-0000-4543-0000-9443d048cdb9",
                            RoleId = "8e445865-0000-0000-0000-9443d048cdb9"
                        },
                        new
                        {
                            UserId = "8e445800-1111-4543-1111-9443d048cdb9",
                            RoleId = "8e445865-aaaa-aaaa-aaaa-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobMarket.Data.Entity.ContractorUser", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Contractor", "AssociatedContractor")
                        .WithMany()
                        .HasForeignKey("ContractorId");

                    b.Navigation("AssociatedContractor");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.CustomerUser", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Customer", "AssociatedCustomer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("AssociatedCustomer");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.Job", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Customer", "AcceptedBy")
                        .WithMany()
                        .HasForeignKey("AcceptedById");

                    b.Navigation("AcceptedBy");
                });

            modelBuilder.Entity("JobMarket.Data.Entity.JobOffer", b =>
                {
                    b.HasOne("JobMarket.Data.Entity.Job", "OfferedJob")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMarket.Data.Entity.Contractor", "OfferedByContractor")
                        .WithMany()
                        .HasForeignKey("OfferedByContractorId");

                    b.Navigation("OfferedByContractor");

                    b.Navigation("OfferedJob");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
